### ISSUE TITLE
[less] css-varvalueexpected when using more complicated variable assignment statements

### ISSUE THREAD

**Issue by kevinramharak** [microsoft/vscode-css-languageservice#141]
The following code will compile correctly on `less@3.9`

```less
// mixin namespace: http://lesscss.org/features/#mixins-feature-namespaces
#util() {
    .mixin() {
        @result: 1;
    }
}

.mixin() {
  @result: 2;
}

// property / value accessors: http://lesscss.org/features/#mixins-feature-mixins-as-functions-feature
@var: #util.mixin()[];
@other: .mixin()[];

:root {
  --var: @var;
  --other: @other;
}
```
The **`#util`** part of `@var: #util.convert...` will signal a `css-varvalueexpected` error as wil the **.** from `@other: .mixin()[]`

Might be related to #134

**Comment by KevinRamharak** [comment]
I just noticed #135, tough my understanding of the source code is very limited so i cannot tell if that PR solves this problem

**Comment by ThePlenkov** [comment]
I can confirm I have same working with less. 

Just copying examples from here http://lesscss.org/features/#maps-feature it's easy to reproduce.

**Comment by SamBrishes** [comment]
Hellow,

Same here using multiple guarded namespaces and ref-link them to a variable as shown below. You can copy and paste this code [on this online Less compiler](https://less.pytes.me) (which uses Less 3.9.0), so its valid Less code!

```less
@color: light;

#scheme() when (@color = light){
    primary: #f0f0f0;
    /* [...] */
}
#scheme() when (@color = dark){
    primary: #121212;
    /* [...] */
}

@primary: #scheme[primary]; // <-- "scheme" gets an error with css-varvalueexpected!

.my-color{
    color: @primary;
}
```

Sincerely,
Sam.
