### ISSUE TITLE
Calc and var

### ISSUE THREAD

**Issue by PsykeDady** [Microsoft/vscode-css-languageservice#146]
When you use a css variable inside a `calc` function, auto-completion doesn't wrap it in a `var()`.
what visual studio does:
```css

:root{
   --heigth-of-viewport: 1vh;
   --half-height: calc( --height-of-viewport / 2);
}
``` 

what should be

```css

:root{
   --heigth-of-viewport: 1vh;
   --half-height: calc( var(--height-of-viewport) / 2);
}
```
