### ISSUE TITLE
[scss] Writing properties directly within nested @media and @supports inside a class disallowed

### ISSUE THREAD

**Issue by TRCYX** [microsoft/vscode-css-languageservice#152]
In the following code, `{ expected scss(css-lcurlyexpected)` is triggered on the three colons inside the nested CSS at-rules:
```scss
.sticky-sidebar-md {
	display: none;

	@supports (position: sticky) {
		@media (min-width: map-get($grid-breakpoints, md)) {
			display: block;
			position: sticky;
			top: 3.5rem + 1rem;
		}
	}
}
```

Commenting out either `@supports` or `@media` makes everything fine.

VSCode version: 1.33.1
