### ISSUE TITLE
Add support for substring matching attribute selectors

### ISSUE THREAD

**Issue by tedconn** [microsoft/vscode-css-languageservice#163]
According to [the level 4 spec](https://www.w3.org/TR/selectors-4/#attribute-substrings) the following syntax is valid:

```css
[class^="icon-"] {
  font-family: "Glpyhs";
}
```

But I am getting an error:

<img width="418" alt="Screenshot 2019-07-08 at 10 05 25" src="https://user-images.githubusercontent.com/38358184/60793422-fd9ae100-a167-11e9-86e1-3df7f4e0fb59.png">
