### ISSUE TITLE
Hover does not work for functions

### ISSUE THREAD

**Issue by mrmlnc** [microsoft/vscode-css-languageservice#196]
The hover provider does not show anything for the function call declaration.

```scss
@function make() {
  @return "something";
}

.micro {
  content: make();
}
```

<img width="307" alt="Annotation 2019-11-27 212038" src="https://user-images.githubusercontent.com/7034281/69749549-c8654e80-115b-11ea-9d5b-a7ab8100e9dd.png">
