### ISSUE TITLE
Hover does not show information about local symbols without CTRL

### ISSUE THREAD

**Issue by mrmlnc** [microsoft/vscode-css-languageservice#199]
Hello, I'm the maintainer of the [`vscode-scss`](https://github.com/mrmlnc/vscode-scss) plugin.

As part of the plugin update, I want to disable IntelliSense providers for the current file. This is necessary in order to not show duplicate symbols in the tooltips (completion, hover, …). Maybe you can suggest something else?

I found that Hover does not display information about the current symbol. Just take a look at the example below:

```scss
@mixin mixin($a: 1, $b) {
	content: 'mixin';
}

@function function() {
	@return 1;
}

$variable: 1;

.test {
  content: $variable + function();

  @include mixin();
}
```

Are you considering repeating the logic of my plugin or TypeScript for this service?

#### Without/With CTRL (without `vscode-scss`)

<img width="293" alt="Annotation 2019-11-29 092800" src="https://user-images.githubusercontent.com/7034281/69848266-acac9600-128a-11ea-97ef-6ce145856e3f.png">

<img width="301" alt="Annotation 2019-11-29 0928001" src="https://user-images.githubusercontent.com/7034281/69848271-afa78680-128a-11ea-80a1-f949bc05ba29.png">

#### With `vscode-scss`

<img width="215" alt="Annotation 2019-11-29 093242" src="https://user-images.githubusercontent.com/7034281/69848467-3b211780-128b-11ea-9ad1-6886b25291b3.png">

#### TypeScript example (without/with CTRL)

<img width="271" alt="Annotation 2019-11-29 0928002" src="https://user-images.githubusercontent.com/7034281/69848491-4b38f700-128b-11ea-8226-c136381d855f.png">

<img width="266" alt="Annotation 2019-11-29 0928003" src="https://user-images.githubusercontent.com/7034281/69848495-4ecc7e00-128b-11ea-9098-54c63ecac902.png">
