### ISSUE TITLE
IE-grid special value trigger error

### ISSUE THREAD

**Issue by Jamie0327** [microsoft/vscode-css-languageservice#211]
the code :
```css
  .wrapper {
            display: -ms-grid;
            display: grid;
            -ms-grid-columns: (1fr)[4];
            grid-template-columns: repeat(4, 1fr);
        }
```
the forth line has a special value'(1fr)[4]'，it triggers error(s)
```
"code": "css-lbracketexpected",
"message": "] expected",
```
even though,it's not fatal,the value above  equals  `1fr 1fr 1fr 1fr`,and does not trigger error.
the code is auto created by a extension(autoprefixer),and it's normal behave in browser.
it just show error things in vscode,I don't know Whether this problem can be fixed?
