### ISSUE TITLE
support media queries level 4 range

### ISSUE THREAD

**Issue by yukulele** [microsoft/vscode-css-languageservice#213]
When I use media query level 4 range:
```css
@media screen and (750px <= width < 900px) {
  html{ color: pink; }
}
```
vscode show this error : `identifier expectedcss(css-identifierexpected)`

**Comment by yoyo837** [comment]
same here:
```less
@keyframes ~"@{ant-prefix}-progress-active" {
  0% {
    width: 0;
    opacity: 0.1;
  }
  20% {
    width: 0;
    opacity: 0.5;
  }
  100% {
    width: 100%;
    opacity: 0;
  }
}
```
