### ISSUE TITLE
variables whose names are bare numbers are not recognized as such

### ISSUE THREAD

**Issue by TomasHubelbauer** [microsoft/vscode-css-languageservice#236]
This CSS code:

```css
.CodeMirror-lines {
  /* Adjust by half a character to account for GitHub spacing */
  --80: 80.5ch;
  --120: 120.5ch;
  --color: silver;

  background: linear-gradient(
    to right,

    transparent,

    /* Render a line at 80 characters */
    transparent var(--80),
    var(--color) calc(var(--80) + 1px),
    transparent 0,

    /* Render a line at 120 characters */
    transparent var(--120),
    var(--color) calc(var(--120) + 1px),
    transparent 0,
    
    transparent
  )

  /* Override GitHub's own stylesheet */
  !important;
}
```

Is highlighted this way in VS Code:

![image](https://user-images.githubusercontent.com/6831144/111148449-ef7fa380-858b-11eb-8072-cd7229101850.png)

When I update the variable names to be strings:

![image](https://user-images.githubusercontent.com/6831144/111148538-09b98180-858c-11eb-862b-2a7e64e8b586.png)

Hopefully this is the right place to report this. Let me know if I can help to fix the issue - where are the rules that determine if a symbol is a CSS variable name located?
