### ISSUE TITLE
@apply error should not affect next line

### ISSUE THREAD

**Issue by johnsoncodehk** [microsoft/vscode-css-languageservice#237]
Related: https://github.com/johnsoncodehk/volar/issues/103
Language: scss

In this code we got 3 errors. `css-semicolonexpected` and `css-ruleorselectorexpected` errors is expected, but `css-lcurlyexpected` expected not.

```scss
.panel {
    @apply p-4 bg-neutral-50; // semi-colon expectedscss(css-semicolonexpected)
    min-height: var(--space-14); // { expectedscss(css-lcurlyexpected) <-- expected no error in this line
} // at-rule or selector expectedscss(css-ruleorselectorexpected)
```
