### ISSUE TITLE
Support latest media syntax: @media not cause validation error

### ISSUE THREAD

**Issue by onemen** [microsoft/vscode-css-languageservice#245]
whenever I use ```@media not``` i see these 3 error:
- ```media query expectedcss(css-mediaqueryexpected)```
- ```{ expectedcss(css-lcurlyexpected)``` in rule **:**
- ```at-rule or selector expectedcss(css-ruleorselectorexpected)``` at the last inner **}**

I see these validation error both on vscode 1.58.0 and 1.59.0-insider

```css
  @media not (-moz-os-version: windows-win7) {
    #TabsToolbar[multibar] toolbarbutton.titlebar-button {
      padding: 12.25px 17px;
      align-self: flex-start;
    }
  }
```

![media-not-error](https://user-images.githubusercontent.com/3650909/125280011-42d8e700-e31d-11eb-9a74-e83f638a8375.png)
