### ISSUE TITLE
Show multiple elements suggestions

### ISSUE THREAD

**Issue by m0ksem** [microsoft/vscode-css-languageservice#249]
```scss
input {
  &:hover, &:focus {
    &::placeholder {
      color: red;
    } 
  }
}
```

![image](https://user-images.githubusercontent.com/23530004/133849494-264917e4-bc1f-4683-acd9-65bd464f3b6b.png)

For example show it as:

`<input :hover ::placeholder> or <input :focus ::placeholder>`

or

```html
<input :hover ::placeholder>
<input :focus ::placeholder>
```

Codepen: https://codepen.io/m0ksem/pen/qBjxxzo
