### ISSUE TITLE
Add support for `<relative‑selector‑list>` in the `:has(…)` pseudo‑class

### ISSUE THREAD

**Issue by ExE-Boss** [microsoft/vscode-css-languageservice#250]
The `:has(…)` pseudo‑class, which is being prototyped in **Blink**, is specified as taking a [`<relative‑selector‑list>`](https://drafts.csswg.org/selectors/#typedef-relative-selector-list).

## See also
- **Chromium** [**Issue 669058:** CSS selectors Level 4: support :has()](https://crbug.com/669058 "Issue 669058: CSS selectors Level 4: support :has()")
- <https://github.com/Igalia/explainers/tree/main/css/has>

---

More broadly, the function syntax for [`<pseudo‑class‑selector>`](https://drafts.csswg.org/selectors/#typedef-pseudo-class-selector) is specified as taking [`<any‑value>`](https://drafts.csswg.org/css-syntax/#typedef-any-value), meaning that the current parser is too restrictive, and also too lax, as `:is(1 - 2)` should result in a warning, since `1 - 2` is not a valid selector, but because `:is(…)` takes a [`<forgiving‑selector‑list>`](https://drafts.csswg.org/selectors/#forgiving-selector), it’s equivalent to `:is()` at runtime, which is a valid selector that matches nothing.

The correct implementation would be to parse pseudo‑class arguments as `<any‑value>`, rather than as <code>&#91; [&lt;complex‑selector‑list&gt;](https://drafts.csswg.org/selectors/#typedef-complex-selector-list) [&#124;](https://drafts.csswg.org/css-values/#comb-one) [&lt;calc‑sum&gt;](https://drafts.csswg.org/css-values/#calc-syntax) &#93;[?](https://drafts.csswg.org/css-values/#mult-opt)</code> as it currently does, and then perform stricter validation of the arguments based on the pseudo‑class/pseudo‑element itself.

**Comment by romainmenke** [comment]
examples : https://github.com/web-platform-tests/wpt/blob/master/css/selectors/invalidation/has-in-adjacent-position.html


```css
div:has(.test) + #subject {
	background-color: red;
}

div:has(> .test) + #subject {
	background-color: green;
}

div:has(~ .test) + #subject {
	background-color: yellow;
}

div:has(+ .test) + #subject {
	background-color: blue;
}

div:has(~ div .test) + #subject {
	background-color: purple;
}

div:has(+ div .test) + # subject {
	background-color: pink;
}
```
