### ISSUE TITLE
Sass variable interpolation broken in an unknown at rule value

### ISSUE THREAD

**Issue by MrSquaare** [microsoft/vscode-css-languageservice#269]
When using variable interpolation in an unknown at rule value, the sass linter reports false errors and the syntax is broken

Example:
```scss
$base: "black";

.text-base {
  @apply text-#{$base};
}
```

![image](https://user-images.githubusercontent.com/28934649/161124992-eea8d8cb-7981-44ae-b2e6-fd2b0d0811dc.png)
