### ISSUE TITLE
Improper double whitespace before !important

### ISSUE THREAD

**Issue by csisy** [microsoft/vscode-css-languageservice#281]
By formatting an scss file, a whitespace is inserted before every `!important`. However, putting `!important` after a variable inserts double spaces instead of one.

For example, the following source

```scss
.my-class {
  font-size: $size !important;
}
```

is formatted into

```scss
.my-class {
  font-size: $size  !important;
}
```

Please note the double space between the `!important` and the variable.
