### ISSUE TITLE
support media queries level 4 range for SCSS

### ISSUE THREAD

**Issue by yukulele** [microsoft/vscode-css-languageservice#312]
Same as #213 but for SCSS

```scss
main {
  background: blue;
  @media (width <= 1024) {
    background: green;
  }
}
```
error:
```
) expected scss(css-rparentexpected)
```
