### ISSUE TITLE
Error when parsing container queries with interpolation inside @each

### ISSUE THREAD

**Issue by max529** [microsoft/vscode-css-languageservice#377]
### Information
- version : 6.2.11
- tested also on vscode : 1.85.1

### Error
Variable interpolation problem for @container rule doesn't work inside @each loop

The issue [#197744](https://github.com/microsoft/vscode/issues/197744) marked as closed does not seem to correct the parsing problem in a loop.

```scss
$size-breakpoints: (
    "xs": 300,
    "sm": 540,
    "md": 720,
    "lg": 960,
    "xl": 1140
);
@each $name, $size in $size-breakpoints {
    @container application (max-width: #{$size+'px'}) {
            
    }
}
```
