### ISSUE TITLE
@container rule being flagged as "unknownAtRules" when nested in SCSS

### ISSUE THREAD

**Issue by dladeira** [microsoft/vscode-css-languageservice#381]
I have the following code snippet in a NUXT project:

```<style lang="scss" scoped>
.item-icon {
    height: 1.6rem;

    &-sm {
        height: 1rem;
    }

    @container (max-height: 100px) {
        display: none;
    }
}
</style>
```

And `@container` is being flagged with `Unknown at rule @containerscss(unknownAtRules)`. The expected behavior is nothing being flagged, as the code runs as expected.

This problem only applies when the rule is nested

**Comment by marcoms** [comment]
This also applies when using native nested CSS which is now gaining adoption

```css
.childEl {
	/* Unknown at rule @containercss(unknownAtRules) */
	@container parentContainer (min-width: 8rem) {
		background: red;
	}
}

/* No error */
@container parentContainer (min-width: 8rem) {
	.childEl {
		background: red;
	}
}

```

**Comment by Jethus** [comment]
Just commenting to say that I'm experiencing the same issue.

``` scss
@mixin container-query($size) {
  $query: map-get($breakpoints, $size);

  @container (min-width: #{$query}) {
    @content;
  }
}
```

![image](https://github.com/microsoft/vscode-css-languageservice/assets/31773638/75a5894d-c524-4832-88b5-7beeb3ab335f)

The code works as intended, just VS Code is flagging `@container` with `Unknown at rule @containerscss(unknownAtRules)`.
