### ISSUE TITLE
[CSS, SCSS, SASS] Wront syntax highlight for `@container` queries

### ISSUE THREAD

**Issue by Profesor08** [microsoft/vscode-css-languageservice#409]
When I use `@container` queries, they broke syntax highlight for entire block

![Image](https://github.com/user-attachments/assets/8e47dce4-2f4b-4a73-a2dc-1306ec0ef4db)

Code example 

```scss
.container {
  display: grid;
  align-content: start;
  gap: 2px;

  @container (min-width: 345px) {
    grid-template-columns: 1fr 1fr;
  }

  @container (min-width: 345px) {
    grid-template-columns: 1fr 1fr;
  }

  @container (min-width: 345px) {
    .item {
      color: red;
    }
  }

  @media (min-width: 345px) {
    grid-template-columns: 1fr 1fr;
  }

  @media (min-width: 345px) {
    .item {
      color: red;
    }
  }
}

@container (min-width: 345px) {
  .container {
    grid-template-columns: 1fr 1fr;
  }
}

@media (min-width: 345px) {
  .container {
    grid-template-columns: 1fr 1fr;
  }
}

```
