### ISSUE TITLE
Property autocomplete + syntax highlighting does not trigger inside custom directive blocks

### ISSUE THREAD

**Issue by fongandrew** [microsoft/vscode-css-languageservice#423]
If you add a new directive to [CSS custom data](https://github.com/microsoft/vscode-css-languageservice/blob/main/docs/customData.md), autocomplete + syntax highlighting does not work within blocks defined by the directive. [Mixins](https://github.com/postcss/postcss-mixins) are one example where this would be useful:

```css
@define-mixin sr-only {
    position: absolute;
    width: 1px;
    height: 1px;
    padding: 0;
    margin: -1px;
    overflow: hidden;
    clip: rect(0, 0, 0, 0);
    white-space: nowrap;
    border-width: 0;
}
```

While this behavior may not be desirable for _all_ directives, it'd be nice to have this as an option for some of them.
