### ISSUE TITLE
Support @view-transition

### ISSUE THREAD

**Issue by gegoune** [microsoft/vscode-css-languageservice#425]
```css
@view-transition {
  navigation: auto;
}
```

https://drafts.csswg.org/css-view-transitions-2/#view-transition-rule
https://developer.mozilla.org/en-US/docs/Web/CSS/@view-transition
https://caniuse.com/?search=%40view-transition

Seems like it's still a draft, but support is pretty good with only Firefox lagging behind out of main browsers

**Comment by kakiuwang-ui** [comment]
This looks fixed now. With vscode-css-languageservice `6.3.10` and `7.0.0-next.2`:

```css
@view-transition {
  navigation: auto;
}
```

produces no "Unknown at rule" diagnostic, and `@view-transition` is offered in at-rule completion (`@v|`). The issue can probably be closed.
