### ISSUE TITLE
less  validation  error

### ISSUE THREAD

**Issue by skcary** [Microsoft/vscode-css-languageservice#46]
.px2rem(@name, @px) {
@{name}: @px / @basesize;
}
提示：
less } expected
less at-rule or selector expected

请支持less的这种写法，谢谢

**Comment by alexlur** [comment]
I have also encountered this issue — you can use this snippet to reproduce it:

```less
.font-face(@source, @target) {
  @font-face { font-family: @source; src: local('@{target}'); }
}
```

which gives the warning `[less] } expected` while the less compiler issues none.
