### ISSUE TITLE
[feature request] Support CSS Custom Properties

### ISSUE THREAD

**Issue by rictic** [Microsoft/vscode-css-languageservice#7]
[CSS Custom Properties](https://drafts.csswg.org/css-variables/) are a relatively new standard. Work is [in progress to support them in Edge](https://wpdev.uservoice.com/forums/257854-microsoft-edge-developer/suggestions/6261292-css-variables), and they're shipping today in [Chrome, Safari, and Firefox](http://caniuse.com/#feat=css-variables).

Custom property usage is fairly straightforward, just an expression like `var(--prop-name)` or `var(--prop-name, exprAsFallbackValue)`. The main tricky bit is that the [allowed syntax for custom property values](https://drafts.csswg.org/css-variables/#syntax) is extremely permissive, allowing stuff like:

```css
body {
  --js-might-read-this: if(x > 5) this.width = 10;

  --my-theme: {
    color: red;
    background: white;
  };
}
```

The latter style does see real world usage today to implement mixins, and is reported as a syntax error in vscode as of v1.7.1.
